export const mockAreasData = [
    {
      id: "area-001",
      name: "Kibera Central",
      community: "Kibera",
      region: "Nairobi",
      country: "Kenya",
      landmarks: "5",
      description: "Central area of Kibera with high population density",
      coordinates: "-1.3152, 36.7822",
      population: "42,500",
      status: "Active",
      createdAt: "2023-01-15",
      updatedAt: "2023-06-22",
    },
    {
      id: "area-002",
      name: "Soweto East",
      community: "Kibera",
      region: "Nairobi",
      country: "Kenya",
      landmarks: "3",
      description: "Eastern section of Kibera with improved infrastructure",
      coordinates: "-1.3142, 36.7902",
      population: "28,300",
      status: "Active",
      createdAt: "2023-01-18",
      updatedAt: "2023-05-12",
    },
    {
      id: "area-003",
      name: "Laini Saba",
      community: "Kibera",
      region: "Nairobi",
      country: "Kenya",
      landmarks: "4",
      description: "Southern area with community centers and schools",
      coordinates: "-1.3182, 36.7862",
      population: "35,700",
      status: "Active",
      createdAt: "2023-02-05",
      updatedAt: "2023-07-18",
    },
    {
      id: "area-004",
      name: "Makina",
      community: "Kibera",
      region: "Nairobi",
      country: "Kenya",
      landmarks: "2",
      description: "Western section with market areas",
      coordinates: "-1.3162, 36.7782",
      population: "31,200",
      status: "Active",
      createdAt: "2023-02-12",
      updatedAt: "2023-08-05",
    },
    {
      id: "area-005",
      name: "Lindi",
      community: "Kibera",
      region: "Nairobi",
      country: "Kenya",
      landmarks: "3",
      description: "Northwestern area with religious institutions",
      coordinates: "-1.3132, 36.7802",
      population: "26,800",
      status: "Active",
      createdAt: "2023-03-01",
      updatedAt: "2023-09-12",
    },
    {
      id: "area-006",
      name: "Silanga",
      community: "Kibera",
      region: "Nairobi",
      country: "Kenya",
      landmarks: "2",
      description: "Southeastern area near the dam",
      coordinates: "-1.3192, 36.7912",
      population: "22,500",
      status: "Active",
      createdAt: "2023-03-15",
      updatedAt: "2023-10-08",
    },
    {
      id: "area-007",
      name: "Kisumu Ndogo",
      community: "Kibera",
      region: "Nairobi",
      country: "Kenya",
      landmarks: "3",
      description: "Small area with mixed housing types",
      coordinates: "-1.3172, 36.7842",
      population: "18,900",
      status: "Active",
      createdAt: "2023-04-02",
      updatedAt: "2023-11-15",
    },
    {
      id: "area-008",
      name: "Gatwekera",
      community: "Kibera",
      region: "Nairobi",
      country: "Kenya",
      landmarks: "4",
      description: "Densely populated area with community projects",
      coordinates: "-1.3122, 36.7832",
      population: "33,600",
      status: "Active",
      createdAt: "2023-04-18",
      updatedAt: "2023-12-05",
    },
    {
      id: "area-009",
      name: "Mashimoni",
      community: "Kibera",
      region: "Nairobi",
      country: "Kenya",
      landmarks: "2",
      description: "Area with improved water access points",
      coordinates: "-1.3142, 36.7852",
      population: "24,700",
      status: "Pending",
      createdAt: "2023-05-10",
      updatedAt: "2024-01-08",
    },
    {
      id: "area-010",
      name: "Kambi Muru",
      community: "Kibera",
      region: "Nairobi",
      country: "Kenya",
      landmarks: "3",
      description: "Area with educational facilities and youth centers",
      coordinates: "-1.3162, 36.7892",
      population: "27,300",
      status: "Inactive",
      createdAt: "2023-05-25",
      updatedAt: "2024-02-12",
    },
  ]
  