export const mockEvents = [
    {
      id: "evt-001",
      title: "Annual Family Reunion",
      type: "Meeting",
      description: "Annual gathering of the Kimani family to celebrate our heritage and strengthen bonds.",
      startDate: "2024-06-15T10:00:00Z",
      endDate: "2024-06-15T18:00:00Z",
      location: "Kimani Family Compound, Nairobi",
      createdBy: "John Kimani",
      createdAt: "2024-04-01T09:30:00Z",
      status: "Approved",
      paymentStatus: "Pending",
      visibility: "Family",
      attendees: 45,
      notes: "Please bring family photos for the archive project.",
      contact: "john.kimani@example.com",
    },
    {
      id: "evt-002",
      title: "Memorial Service for Elder Wanjiku",
      type: "Funeral",
      description: "A memorial service to honor the life and legacy of Elder Wanjiku, a respected community leader.",
      startDate: "2024-05-20T14:00:00Z",
      endDate: "2024-05-20T17:00:00Z",
      location: "Community Center, Kiambu",
      createdBy: "Mary Njeri",
      createdAt: "2024-04-05T11:45:00Z",
      status: "Published",
      paymentStatus: "Paid",
      visibility: "Community",
      attendees: 120,
      notes: "The family requests donations to the community school fund in lieu of flowers.",
      contact: "mary.njeri@example.com",
    },
    {
      id: "evt-003",
      title: "Kimani-Ochieng Wedding Ceremony",
      type: "Wedding",
      description: "Wedding ceremony celebrating the union of James Kimani and Sarah Ochieng.",
      startDate: "2024-07-10T11:00:00Z",
      endDate: "2024-07-10T23:00:00Z",
      location: "Serena Hotel, Nairobi",
      createdBy: "James Kimani",
      createdAt: "2024-03-15T08:20:00Z",
      status: "Pending",
      paymentStatus: "Pending",
      visibility: "Clan",
      attendees: 200,
      notes: "Black tie event. RSVP required by June 15.",
      contact: "james.kimani@example.com",
    },
    {
      id: "evt-004",
      title: "Mwangi Clan Annual Meeting",
      type: "Meeting",
      description: "Annual meeting to discuss clan affairs, projects, and future plans.",
      startDate: "2024-08-05T09:00:00Z",
      endDate: "2024-08-05T16:00:00Z",
      location: "Mwangi Cultural Center, Nyeri",
      createdBy: "Peter Mwangi",
      createdAt: "2024-04-10T14:30:00Z",
      status: "Approved",
      paymentStatus: "Paid",
      visibility: "Clan",
      attendees: 75,
      notes: "Agenda includes scholarship fund updates and cultural preservation initiatives.",
      contact: "peter.mwangi@example.com",
    },
    {
      id: "evt-005",
      title: "Nairobi Region Cultural Festival",
      type: "Festival",
      description: "A celebration of the diverse cultures within the Nairobi region with music, food, and art.",
      startDate: "2024-09-15T10:00:00Z",
      endDate: "2024-09-17T20:00:00Z",
      location: "Uhuru Park, Nairobi",
      createdBy: "Sarah Wambui",
      createdAt: "2024-03-25T16:15:00Z",
      status: "Pending",
      paymentStatus: "Pending",
      visibility: "Region",
      attendees: 500,
      notes: "Vendors and performers should register by August 1.",
      contact: "sarah.wambui@example.com",
    },
    {
      id: "evt-006",
      title: "Omondi Family Birthday Celebration",
      type: "Birthday",
      description: "Celebration of Elder Omondi's 80th birthday.",
      startDate: "2024-05-30T15:00:00Z",
      endDate: "2024-05-30T21:00:00Z",
      location: "Omondi Residence, Kisumu",
      createdBy: "David Omondi",
      createdAt: "2024-04-12T10:10:00Z",
      status: "Published",
      paymentStatus: "Paid",
      visibility: "Family",
      attendees: 35,
      notes: "Please bring stories and memories to share.",
      contact: "david.omondi@example.com",
    },
    {
      id: "evt-007",
      title: "Kikuyu Sub-Clan Heritage Day",
      type: "Cultural",
      description: "A day dedicated to preserving and celebrating the heritage of the Kikuyu sub-clan.",
      startDate: "2024-10-05T09:00:00Z",
      endDate: "2024-10-05T18:00:00Z",
      location: "Community Grounds, Kiambu",
      createdBy: "Joseph Kamau",
      createdAt: "2024-04-08T13:45:00Z",
      status: "Rejected",
      paymentStatus: "Pending",
      visibility: "SubClan",
      attendees: 150,
      notes: "Activities include traditional dances, storytelling, and crafts.",
      contact: "joseph.kamau@example.com",
    },
    {
      id: "evt-008",
      title: "Kenya National Unity Conference",
      type: "Conference",
      description: "A conference bringing together representatives from all regions to discuss national unity.",
      startDate: "2024-11-10T08:00:00Z",
      endDate: "2024-11-12T17:00:00Z",
      location: "KICC, Nairobi",
      createdBy: "Elizabeth Otieno",
      createdAt: "2024-04-15T09:00:00Z",
      status: "Pending",
      paymentStatus: "Pending",
      visibility: "Country",
      attendees: 300,
      notes: "Registration required. Accommodation available for out-of-town delegates.",
      contact: "elizabeth.otieno@example.com",
    },
  ]
  