export const mockCommunities = [
  {
    id: "comm-001",
    name: "Eastlands Community",
    region: "Nairobi",
    description:
      "A vibrant community in the eastern part of Nairobi with a rich cultural heritage and strong community bonds.",
    population: 25000,
    status: "Active",
    createdAt: "2023-05-15",
    image: "/placeholder.svg?height=400&width=600",
    stats: {
      families: 5200,
      members: 18500,
      events: 45,
      projects: 12,
    },
  },
  {
    id: "comm-002",
    name: "Westlands Community",
    region: "Nairobi",
    description:
      "An affluent community in the western part of Nairobi known for its modern infrastructure and diverse population.",
    population: 18500,
    status: "Active",
    createdAt: "2023-06-22",
    image: "/placeholder.svg?height=400&width=600",
    stats: {
      families: 3800,
      members: 14200,
      events: 38,
      projects: 15,
    },
  },
  {
    id: "comm-003",
    name: "Mombasa Old Town",
    region: "Mombasa",
    description: "A historic community with rich Swahili culture and architecture, located in the heart of Mombasa.",
    population: 12000,
    status: "Active",
    createdAt: "2023-04-10",
    image: "/placeholder.svg?height=400&width=600",
    stats: {
      families: 2500,
      members: 9800,
      events: 32,
      projects: 8,
    },
  },
  {
    id: "comm-004",
    name: "Kisumu Lakeside",
    region: "Kisumu",
    description:
      "A community situated along the shores of Lake Victoria, known for fishing traditions and vibrant cultural practices.",
    population: 15000,
    status: "Inactive",
    createdAt: "2023-07-05",
    image: "/placeholder.svg?height=400&width=600",
    stats: {
      families: 3100,
      members: 12500,
      events: 28,
      projects: 6,
    },
  },
  {
    id: "comm-005",
    name: "Nakuru Town",
    region: "Nakuru",
    description:
      "A growing community in Nakuru with a mix of urban and rural characteristics, known for its agricultural activities.",
    population: 22000,
    status: "Active",
    createdAt: "2023-08-18",
    image: "/placeholder.svg?height=400&width=600",
    stats: {
      families: 4500,
      members: 17800,
      events: 35,
      projects: 10,
    },
  },
  {
    id: "comm-006",
    name: "Eldoret Highlands",
    region: "Uasin Gishu",
    description: "A community in the highlands of Uasin Gishu, known for athletics and agricultural production.",
    population: 19500,
    status: "Pending",
    createdAt: "2023-09-30",
    image: "/placeholder.svg?height=400&width=600",
    stats: {
      families: 4000,
      members: 16200,
      events: 30,
      projects: 9,
    },
  },
  {
    id: "comm-007",
    name: "Malindi Coastal",
    region: "Kilifi",
    description: "A coastal community in Kilifi with a blend of tourism, fishing, and traditional Swahili culture.",
    population: 14000,
    status: "Active",
    createdAt: "2023-10-12",
    image: "/placeholder.svg?height=400&width=600",
    stats: {
      families: 2900,
      members: 11500,
      events: 25,
      projects: 7,
    },
  },
  {
    id: "comm-008",
    name: "Kitale Agricultural",
    region: "Trans Nzoia",
    description: "A farming community in Trans Nzoia known for maize production and agricultural innovation.",
    population: 17000,
    status: "Active",
    createdAt: "2023-11-05",
    image: "/placeholder.svg?height=400&width=600",
    stats: {
      families: 3500,
      members: 14000,
      events: 22,
      projects: 11,
    },
  },
]
