// Mock data for people management

export const families = [
  "Addo Family",
  "Mensah Family",
  "Osei Family",
  "Owusu Family",
  "Boateng Family",
  "Acheampong Family",
  "Agyemang Family",
  "Asante Family",
  "Danso Family",
  "Frimpong Family",
]

export const clans = [
  "Asona Clan",
  "Agona Clan",
  "Ekuona Clan",
  "Bretuo Clan",
  "Asenie Clan",
  "Aduana Clan",
  "Asakyiri Clan",
  "Oyoko Clan",
]

export const ethnicGroups = ["Akan", "Ewe", "Ga-Adangbe", "Mole-Dagbani", "Guan", "Gurma", "Grusi", "Mande"]

export const regions = [
  "Greater Accra",
  "Ashanti",
  "Eastern",
  "Western",
  "Central",
  "Volta",
  "Northern",
  "Upper East",
  "Upper West",
  "Bono East",
  "Ahafo",
  "Bono",
  "North East",
  "Savannah",
  "Oti",
  "Western North",
]

export const mockPeopleData = [
  {
    id: "p1",
    name: "Kwame Addo",
    gender: "male",
    family: "Addo Family",
    clan: "Asona Clan",
    ethnicGroup: "Akan",
    region: "Greater Accra",
    status: "active",
    lifeStatus: "alive",
    idNumber: "GHA-123456789",
    notes: "Family head and community elder",
    birthRecord: {
      date: "1965-05-15",
      place: "Accra",
      certificateNumber: "BC-12345",
      registeredBy: "Ghana Health Service",
    },
    deathRecord: null,
    familyLinks: [
      {
        id: "p2",
        name: "Ama Addo",
        relationshipType: "spouse",
      },
      {
        id: "p3",
        name: "Kofi Addo",
        relationshipType: "child",
      },
    ],
  },
  {
    id: "p2",
    name: "Ama Addo",
    gender: "female",
    family: "Addo Family",
    clan: "Ekuona Clan",
    ethnicGroup: "Akan",
    region: "Greater Accra",
    status: "active",
    lifeStatus: "alive",
    idNumber: "GHA-987654321",
    notes: "Teacher at local school",
    birthRecord: {
      date: "1970-08-22",
      place: "Kumasi",
      certificateNumber: "BC-67890",
      registeredBy: "Ghana Health Service",
    },
    deathRecord: null,
    familyLinks: [
      {
        id: "p1",
        name: "Kwame Addo",
        relationshipType: "spouse",
      },
      {
        id: "p3",
        name: "Kofi Addo",
        relationshipType: "child",
      },
    ],
  },
  {
    id: "p3",
    name: "Kofi Addo",
    gender: "male",
    family: "Addo Family",
    clan: "Asona Clan",
    ethnicGroup: "Akan",
    region: "Greater Accra",
    status: "active",
    lifeStatus: "alive",
    idNumber: "GHA-456789123",
    notes: "University student",
    birthRecord: {
      date: "1995-11-10",
      place: "Accra",
      certificateNumber: "BC-54321",
      registeredBy: "Ghana Health Service",
    },
    deathRecord: null,
    familyLinks: [
      {
        id: "p1",
        name: "Kwame Addo",
        relationshipType: "parent",
      },
      {
        id: "p2",
        name: "Ama Addo",
        relationshipType: "parent",
      },
    ],
  },
  {
    id: "p4",
    name: "Yaw Mensah",
    gender: "male",
    family: "Mensah Family",
    clan: "Bretuo Clan",
    ethnicGroup: "Akan",
    region: "Ashanti",
    status: "active",
    lifeStatus: "alive",
    idNumber: "GHA-789123456",
    notes: "Businessman and entrepreneur",
    birthRecord: {
      date: "1975-03-28",
      place: "Kumasi",
      certificateNumber: "BC-98765",
      registeredBy: "Ghana Health Service",
    },
    deathRecord: null,
    familyLinks: [
      {
        id: "p5",
        name: "Akosua Mensah",
        relationshipType: "spouse",
      },
    ],
  },
  {
    id: "p5",
    name: "Akosua Mensah",
    gender: "female",
    family: "Mensah Family",
    clan: "Oyoko Clan",
    ethnicGroup: "Akan",
    region: "Ashanti",
    status: "active",
    lifeStatus: "alive",
    idNumber: "GHA-321654987",
    notes: "Doctor at regional hospital",
    birthRecord: {
      date: "1978-12-05",
      place: "Accra",
      certificateNumber: "BC-45678",
      registeredBy: "Ghana Health Service",
    },
    deathRecord: null,
    familyLinks: [
      {
        id: "p4",
        name: "Yaw Mensah",
        relationshipType: "spouse",
      },
    ],
  },
  {
    id: "p6",
    name: "Kwesi Osei",
    gender: "male",
    family: "Osei Family",
    clan: "Aduana Clan",
    ethnicGroup: "Akan",
    region: "Eastern",
    status: "inactive",
    lifeStatus: "deceased",
    idNumber: "GHA-654987321",
    notes: "Former chief of village",
    birthRecord: {
      date: "1940-07-12",
      place: "Koforidua",
      certificateNumber: "BC-13579",
      registeredBy: "Ghana Health Service",
    },
    deathRecord: {
      date: "2020-09-18",
      place: "Koforidua",
      cause: "Natural causes",
      certificateNumber: "DC-24680",
    },
    familyLinks: [
      {
        id: "p7",
        name: "Abena Osei",
        relationshipType: "spouse",
      },
      {
        id: "p8",
        name: "Kojo Osei",
        relationshipType: "child",
      },
    ],
  },
  {
    id: "p7",
    name: "Abena Osei",
    gender: "female",
    family: "Osei Family",
    clan: "Asenie Clan",
    ethnicGroup: "Akan",
    region: "Eastern",
    status: "active",
    lifeStatus: "alive",
    idNumber: "GHA-987321654",
    notes: "Village elder",
    birthRecord: {
      date: "1945-04-30",
      place: "Koforidua",
      certificateNumber: "BC-97531",
      registeredBy: "Ghana Health Service",
    },
    deathRecord: null,
    familyLinks: [
      {
        id: "p6",
        name: "Kwesi Osei",
        relationshipType: "spouse",
      },
      {
        id: "p8",
        name: "Kojo Osei",
        relationshipType: "child",
      },
    ],
  },
  {
    id: "p8",
    name: "Kojo Osei",
    gender: "male",
    family: "Osei Family",
    clan: "Aduana Clan",
    ethnicGroup: "Akan",
    region: "Eastern",
    status: "active",
    lifeStatus: "alive",
    idNumber: "GHA-321987654",
    notes: "Teacher and community leader",
    birthRecord: {
      date: "1970-10-25",
      place: "Koforidua",
      certificateNumber: "BC-86420",
      registeredBy: "Ghana Health Service",
    },
    deathRecord: null,
    familyLinks: [
      {
        id: "p6",
        name: "Kwesi Osei",
        relationshipType: "parent",
      },
      {
        id: "p7",
        name: "Abena Osei",
        relationshipType: "parent",
      },
    ],
  },
  {
    id: "p9",
    name: "Akua Owusu",
    gender: "female",
    family: "Owusu Family",
    clan: "Asakyiri Clan",
    ethnicGroup: "Akan",
    region: "Central",
    status: "active",
    lifeStatus: "alive",
    idNumber: "GHA-456123789",
    notes: "Nurse at local clinic",
    birthRecord: {
      date: "1985-02-14",
      place: "Cape Coast",
      certificateNumber: "BC-75319",
      registeredBy: "Ghana Health Service",
    },
    deathRecord: null,
    familyLinks: [],
  },
  {
    id: "p10",
    name: "Kwabena Boateng",
    gender: "male",
    family: "Boateng Family",
    clan: "Agona Clan",
    ethnicGroup: "Akan",
    region: "Western",
    status: "inactive",
    lifeStatus: "deceased",
    idNumber: "GHA-789456123",
    notes: "Former fisherman",
    birthRecord: {
      date: "1950-06-20",
      place: "Takoradi",
      certificateNumber: "BC-95173",
      registeredBy: "Ghana Health Service",
    },
    deathRecord: {
      date: "2022-01-05",
      place: "Takoradi",
      cause: "Heart failure",
      certificateNumber: "DC-86420",
    },
    familyLinks: [],
  },
]
